/* 
 * File:   mcal_interrupt_gen_cfg.h
 * Author: Ehab
 *
 * Created on 08 ?????, 2023, 04:46 ?
 */

#ifndef MCAL_INTERRUPT_GEN_CFG_H
#define	MCAL_INTERRUPT_GEN_CFG_H

/* ----------------- Macro Declarations ----------------- */
#define INTERRUPT_FEATURE_ENABLE     1

//#define INTERRUPT_PRIORITY_LEVELS    INTERRUPT_FEATURE_ENABLE

#define EXT_INTERRUPT_INTx_FEATURE_ENABLE    INTERRUPT_FEATURE_ENABLE
#define EXT_INTERRUPT_RBx_FEATURE_ENABLE     INTERRUPT_FEATURE_ENABLE

#define ADC_INTERRUPT_FEATURE                INTERRUPT_FEATURE_ENABLE

#define TIMER0_INTERRUPT_FEATURE             INTERRUPT_FEATURE_ENABLE
#define TIMER1_INTERRUPT_FEATURE             INTERRUPT_FEATURE_ENABLE
#define TIMER2_INTERRUPT_FEATURE             INTERRUPT_FEATURE_ENABLE
#define TIMER3_INTERRUPT_FEATURE             INTERRUPT_FEATURE_ENABLE

#define CCP1_INTERRUPT_FEATURE               INTERRUPT_FEATURE_ENABLE
#define CCP2_INTERRUPT_FEATURE               INTERRUPT_FEATURE_ENABLE

#define EUSART_TX_INTERRUPT_FEATURE          INTERRUPT_FEATURE_ENABLE
#define EUSART_RX_INTERRUPT_FEATURE          INTERRUPT_FEATURE_ENABLE

#define MSSP_I2C_INTERRUPT_FEATURE           INTERRUPT_FEATURE_ENABLE
#define MSSP_I2C_BUS_COL_INTERRUPT_FEATURE   INTERRUPT_FEATURE_ENABLE

#define MSSP_SPI_INTERRUPT_FEATURE           INTERRUPT_FEATURE_ENABLE

#endif	/* MCAL_INTERRUPT_GEN_CFG_H */

